version: '3'

services:
  voicevox_engine_wine:
    image: voicevox_engine_wine
    build:
      context: ./voicevox_engine_wine
      args:
        - VIRTUAL_PORT=${VIRTUAL_PORT}
    ports:
      - "127.0.0.1:${VIRTUAL_PORT}:${VIRTUAL_PORT}"
    volumes:
      - ${DIST_DIR}:/opt/voicevox
    restart: always
